"""Updated response detail table

Revision ID: 075d8a8581b3
Revises: 941c6d8d65a3
Create Date: 2026-10-08 11:45:40.623217

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '075d8a8581b3'
down_revision: Union[str, Sequence[str], None] = '941c6d8d65a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('response_details', 'response_value',
               existing_type=mysql.TEXT(),
               type_=sa.JSON(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('response_details', 'response_value',
               existing_type=sa.JSON(),
               type_=mysql.TEXT(),
               existing_nullable=True)
    # ### end Alembic commands ###
